version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
    environment:
      - SONAR_FORCEAUTHENTICATION=false
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8082:8080
    volumes:
      - jenkinsvol1:/var/jenkins_home
    networks:
      - mynetwork
networks:
  mynetwork:

volumes:
  jenkinsvol1: